- hosts: localhost
  become: true
  pre_tasks:
    - name: update pacman
      pacman: 
        update_cache: true
        upgrade: yes
        tags:
          - core
  tasks:
    - include: tasks/git.yml
    - include: tasks/zsh.yml
